import React, { Component, Image } from 'react';
import './Chart.css'

class Chart extends Component{
    
    render(){
        const Style={
            display:"inline-block",
            width:"20%",
            height:"20%"
        }
      return(
        <div id="section">
          <table border="1">
            <tr>
              <th>기업이름</th>
              <th>현재가</th>
              <th>전일비</th>
              <th>등락률</th>
              <th>거래량</th>
              <th>시가</th>
              <th>고가</th>
              <th>저가</th>
              <th>PER</th>
              <th>EPS</th>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
            <tr>
              <td>Data1</td>
              <td>Data2</td>
              <td>Data3</td>
              <td>Data4</td>
              <td>Data5</td>
              <td>Data6</td>
              <td>Data7</td>
              <td>Data8</td>
              <td>Data9</td>
              <td>Data10</td>
            </tr>
          </table>
        </div>
      );
    }
  }

  export default Chart;